cookbook/src/Components/Signin.js, cookbook/src/Components/Signup.js
Add Signin component and fix small bug in Signup component.
- Manually through local React host
=> Signin Component

Backend/package-lock.json, Backend/package.json, Backend/prisma/datamodel.prisma, Backend/prisma/prisma.yml, Backend/src/resolvers/AuthPayload.js, Backend/src/utils.js
Please include a summary of the change and a link to which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
=> Prisma Database

cookbook/public/index.html, cookbook/src/Components/Signin.js, cookbook/src/Components/Signup.js, cookbook/src/Styles/css/index.css, cookbook/src/Styles/less/app.less, cookbook/src/Styles/less/index.less, cookbook/src/Styles/less/mixins.less, cookbook/src/Styles/less/signup.less, cookbook/src/Styles/less/variables.less
Signup Component is styled to match the mockups.
Manually in local React host.
=> Signup Component Styles

Backend/.env, Backend/.gitignore, Backend/package-lock.json, Backend/package.json, Backend/prisma/datamodel.prisma, Backend/prisma/prisma.yml, Backend/src/generated/prisma.graphql
Deploy Prisma DB to heroku and change db endpoint for graphql server
Manually tested using Graphql playground
=> Deploy Prisma DB to Heroku

cookbook/src/App.js, cookbook/src/Components/Signin.js, cookbook/src/Components/Signup.js, cookbook/src/Styles/css/index.css, cookbook/src/Styles/less/index.less, cookbook/src/Styles/less/mixins.less, cookbook/src/Styles/less/signin.less, cookbook/src/Styles/less/signup.less
I styled the Signin component to match the Signup component. I also added autocomplete fields to the username and password to comply with a google chromium warning in the console.
Tested manually on localhost React app.
=> Signin Styles Front End

netlify.toml
Add configuration for netlify deployment.
Manually tested on netlify
=> Netlify configuration

Backend/prisma/datamodel.prisma, Backend/src/generated/prisma.graphql
Added instruction and ingredient models to prisma and generated the prisma.graphql
Tested manually in graphql playground
=> Instructions model

cookbook/src/Components/Signin.js, cookbook/src/Components/Signup.js, cookbook/src/Styles/css/index.css, cookbook/src/Styles/less/LandingPage.less, cookbook/src/Styles/less/signin.less, cookbook/src/Styles/less/signup.less
Deploy Prisma DB to heroku and change db endpoint for graphql server
Manually tested local react server. Will be working on live server once this is merged.
=> Front end header

cookbook/src/App.js, cookbook/src/Components/Footer.js, cookbook/src/Components/Header.js, cookbook/src/Components/LandingPage.js, cookbook/src/Components/NavIcon.js, cookbook/src/Styles/css/index.css, cookbook/src/Styles/less/LandingPage.less, cookbook/src/Styles/less/app.less, cookbook/src/Styles/less/footer.less, cookbook/src/Styles/less/header.less, cookbook/src/Styles/less/index.less, cookbook/src/Styles/less/mixins.less, cookbook/src/Styles/less/nav-icon.less, cookbook/src/Styles/less/navIcon.less, cookbook/src/Styles/less/signin.less, cookbook/src/Styles/less/signup.less, cookbook/src/Styles/less/variables.less
=> Footer & Landing Page styles

cookbook/package.json, cookbook/src/App.js, cookbook/src/Components/Calendar.js, cookbook/src/Components/Create.js, cookbook/src/Components/Dashboard.js, cookbook/src/Components/Home.js, cookbook/src/Components/Nav.js, cookbook/src/Components/Recipes.js, cookbook/src/Components/Settings.js, cookbook/src/Styles/css/index.css, cookbook/src/Styles/less/app.less, cookbook/src/Styles/less/header.less, cookbook/src/Styles/less/home.less, cookbook/src/Styles/less/index.less, cookbook/yarn.lock
Implement Routing to different pages and add placeholders for components.
=> Implement Navigation sidebar for Home page

Backend/package-lock.json, Backend/package.json, Backend/prisma/datamodel.prisma, Backend/prisma/prisma.yml, Backend/src/generated/prisma.graphql, Backend/src/resolvers/Mutation.js, Backend/src/schema.graphql, Backend/src/stripe.js, cookbook/.env, cookbook/package.json, cookbook/src/Components/Home/SubPages/Settings.js, cookbook/yarn.lock
Stripe integration completed on FE and BE. Tested on stripe's website to confirm that test charge was processed and received.
=> Stripe integration

cookbook/package.json, cookbook/src/Components/Home/Home.js, cookbook/src/Components/Home/SubPages/Billing.js, cookbook/src/Components/Home/SubPages/Create.js, cookbook/src/Components/Home/SubPages/Preview.js, cookbook/src/Styles/css/index.css, cookbook/src/Styles/less/app.less, cookbook/src/Styles/less/create.less, cookbook/src/Styles/less/home.less, cookbook/src/Styles/less/index.less, cookbook/src/Styles/less/recipe-preview.less, cookbook/src/utils/scraper.js, cookbook/yarn.lock
Implement preview scraper for Create Page
=> Recipe preview scraper

cookbook/src/Components/Home/SubPages/Create.js, cookbook/src/Components/Home/SubPages/Preview.js, cookbook/src/Styles/less/create.less, cookbook/src/utils/scraper.js
Can now extract ingredients and recipes from 1 of the 2 whitelisted website.
=> Update scraper and create page recipe buttons

cookbook/src/Components/Home/SubPages/Recipes.js, cookbook/src/Styles/css/index.css, cookbook/src/Styles/less/recipes.less
I added environment variables to differentiate between Development and Production. I deleted the `.env` inside cookbook, and made the `.gitignore` only on the root folder of the project. 
Manually with localhost.
=> Recipe CSS + Fixed BE+FE Connection. Deployed Servers work

Backend/package-lock.json, cookbook/src/Components/Home/SubPages/Create.js, cookbook/src/Components/SubComponents/DatePicker.js, cookbook/src/Components/SubComponents/PickDay.js
I added a calendar on the create page so users can schedule a date while creating a recipe.
Tested manually on local machine.
=> Assign date to recipes

Backend/package-lock.json, cookbook/src/Components/Home/SubPages/Preview.js, cookbook/src/utils/scraper.js
Complete full functional scraper
=> Complete scraper

Backend/prisma/datamodel.prisma, cookbook/src/Auth/Auth.js, cookbook/src/Components/Home/SubPages/Buttons.js, cookbook/src/Components/Home/SubPages/Calendar.js, cookbook/src/Components/Home/SubPages/Create.js, cookbook/src/Components/SubComponents/Header.js
ApolloClient sends the id_token from Auth0 to our server with every request. The server decodes the token with jwt and stores the user info on the context, which can be used by mutations and queries.
Tested locally in graphql playground and local react host.
=> Buttons component

Backend/src/resolvers/Mutation.js, cookbook/public/index.html, cookbook/src/Components/Home/SubPages/Buttons.js, cookbook/src/Components/Home/SubPages/Create.js, cookbook/src/Components/Landing/LandingPage.js
Build out basic functionality of the recipes component.
Tested manually on local machine.
=> working on create save mutation

Backend/src/resolvers/Mutation.js, Backend/src/schema.graphql, cookbook/src/Components/Home/SubPages/Create.js, cookbook/src/utils/scraper.js
Add instructions and ingredients mutations to Create component.
Tested manually on local machine
=> Instructions mutation

cookbook/src/Components/Home/SubPages/Calendar.js, cookbook/src/Components/Home/SubPages/Create.js
Add instructions and ingredients mutations to Create component.
Tested manually on local machine
=> added query to calendar

Backend/package-lock.json, Backend/package.json
=> Fix heroku deploy bug

cookbook/src/utils/scraper.js
quick change to all origins url
=> add s to https for allorigins

Backend/src/resolvers/Query.js, cookbook/src/Components/Home/SubPages/RecipeCard.js, cookbook/src/Components/Home/SubPages/Recipes.js
Made some changes to Recipes and RecipeCard components.
Manually tested in react.
=> Recipes Page

cookbook/public/index.html, cookbook/src/Components/SubComponents/Footer.js, cookbook/src/Components/SubComponents/Header.js, cookbook/src/Styles/css/index.css, cookbook/src/Styles/less/app.less, cookbook/src/Styles/less/footer.less, cookbook/src/Styles/less/header.less, cookbook/src/Styles/less/variables.less, cookbook/src/designs/Logo/CookBookLogo.svg
Footer is fully styled and responsive with mobile-first design.
Tested manually on local machine
=> Fully Responsive Footer Styling

cookbook/public/index.html, cookbook/src/Components/Home/SubPages/Calendar.js, cookbook/src/Components/SubComponents/Portal.js
Footer is fully styled and responsive with mobile-first design.
Tested manually on local machine
=> Calendar data persistance and Portal

cookbook/src/Components/Home/SubPages/RecipeCard.js, cookbook/src/Components/SubComponents/CardSchedule.js, cookbook/src/Components/SubComponents/Header.js, cookbook/src/Styles/css/index.css, cookbook/src/Styles/less/recipe-card.less
Recipes with multiple events will have a scrolling event window on their card.
Tested manually on local machine.
=> Event scrolling

cookbook/src/Components/Home/SubPages/Calendar.js, cookbook/src/Components/Home/SubPages/Create.js, cookbook/src/Components/SubComponents/CardSchedule.js, cookbook/src/Styles/css/index.css, cookbook/src/Styles/less/calendar.less, cookbook/src/Styles/less/portal.less, cookbook/src/Styles/less/recipe-card.less
_ Minor styling change to Modal
Manually tested in react.
=> Modal styling

cookbook/src/Components/Home/SubPages/RecipeView.js, cookbook/src/Styles/css/index.css, cookbook/src/Styles/less/recipe-view.less
Error on recipe-view's instructions fixed.
Fixes # (issue)
- [ X] My code follows the style guidelines of this project
=> error fixed

cookbook/src/Components/Home/SubPages/Calendar.js, cookbook/src/Styles/css/index.css, cookbook/src/Styles/less/calendar.less, cookbook/src/Styles/less/header.less
Calendar page styled and fully-responsive. Fixed signout button styles.
Fixes # (issue)
=> calendar page styled and responsive

cookbook/src/Styles/css/index.css, cookbook/src/Styles/less/recipes.less
fixed styled for icons on recipes page.
=> buttons style fixed

Backend/src/index.js
Change Netlify URLs in index.js to our new deployment.
=> change backend Netlify urls to our newly deployed url
